const PACKAGE_PERIOD ={
    MIN_PERIOD:"3m",
    MIDDLE_PERIOD:"6m",
    MAX_PERIOD:"12m"
}
const PACKAGE_PRICE = {
    MIN_PERIOD:"5000",
    MIDDLE_PERIOD:"10000",
    MAX_PERIOD:"15000"
}
module.exports = {PACKAGE_PERIOD,PACKAGE_PRICE}